#include "components/Affects.h"


namespace ring::components {

    const std::map<int, std::string> affects = {
            {AFF_BLIND,          "BLIND"},
            {AFF_INVISIBLE,      "INVIS"},
            {AFF_DETECT_ALIGN,   "DET-ALIGN"},
            {AFF_DETECT_INVIS,   "DET_INVIS"},
            {AFF_DETECT_MAGIC,   "DET-MAGIC"},
            {AFF_SENSE_LIFE,     "SENSE-LIFE"},
            {AFF_WATERWALK,      "WATWALK"},
            {AFF_SANCTUARY,      "BARRIER"},
            {AFF_GROUP,          "GROUP"},
            {AFF_CURSE,          "CURSE"},
            {AFF_INFRAVISION,    "INFRAVISION"},
            {AFF_POISON,         "POISON"},
            {AFF_WEAKENED_STATE, "WEAKENED"},
            {AFF_PROTECT_GOOD,   "PROT-GOOD"},
            {AFF_SLEEP,          "SLEEP"},
            {AFF_NOTRACK,        "NO_TRACK"},
            {AFF_UNDEAD,         "UNDEAD"},
            {AFF_PARALYZE,       "STONED"},
            {AFF_SNEAK,          "SNEAK"},
            {AFF_HIDE,           "HIDE"},
            {AFF_CHARM,          "CHARM"},
            {AFF_FLYING,         "FLYING"},
            {AFF_WATERBREATH,    "WATER-BREATH"},
            {AFF_ANGELIC,        "ANGELIC"},
            {AFF_ETHEREAL,       "ETHEREAL"},
            {AFF_MAGICONLY,      "MAGICONLY"},
            {AFF_NEXTPARTIAL,    "NEXTPARTIAL"},
            {AFF_NEXTNOACTION,   "NEXTNOACT"},
            {AFF_STUNNED,        "STUNNED"},
            {AFF_TAMED,          "TAME"},
            {AFF_CDEATH,         "CDEATH"},
            {AFF_SPIRIT,         "SPIRIT"},
            {AFF_STONESKIN,      "STONESKIN"},
            {AFF_SUMMONED,       "SUMMONED"},
            {AFF_CELESTIAL,      "CELESTIAL"},
            {AFF_FIENDISH,       "FIENDISH"},
            {AFF_FIRESHIELD,     "FIRESHIELD"},
            {AFF_LOW_LIGHT,      "LOW_LIGHT"},
            {AFF_ZANZOKEN,       "ZANZOKEN"},
            {AFF_KNOCKED,        "KO"},
            {AFF_MIGHT,          "MIGHT"},
            {AFF_FLEX,           "FLEX"},
            {AFF_GENIUS,         "GENIUS"},
            {AFF_BLESS,          "BLESS"},
            {AFF_BURNT,          "BURNT"},
            {AFF_BURNED,         "BURNED"},
            {AFF_MBREAK,         "MBREAK"},
            {AFF_HASS,           "HASS"},
            {AFF_FUTURE,         "FS"},
            {AFF_PARA,           "PARALYZE"},
            {AFF_INFUSE,         "INFUSED"},
            {AFF_ENLIGHTEN,      "ENLIGHT"},
            {AFF_FROZEN,         "FROZOWNED"},
            {AFF_FIRESHIELD,     "FIRESHIELD"},
            {AFF_ENSNARED,       "ENSNARED"},
            {AFF_HAYASA,         "HAYASA"},
            {AFF_PURSUIT,        "PURSUED"},
            {AFF_WITHER,         "WITHERED"},
            {AFF_HYDROZAP,       "HYDROZAP"},
            {AFF_POSITION,       "POSITION"},
            {AFF_SHOCKED,        "SHOCKED"},
            {AFF_METAMORPH,      "METAMORPH"},
            {AFF_HEALGLOW,       "HEALING-GLOW"},
            {AFF_EARMOR,         "ALGIZ RUNE"},
            {AFF_ECHAINS,        "OAGAZ RUNE"},
            {AFF_WUNJO,          "WUNJO RUNE"},
            {AFF_POTENT,         "PURISAZ RUNE"},
            {AFF_ASHED,          "ASHED"},
            {AFF_LIQUEFIED,      "LIQUEFIED"},
            {AFF_SHELL,          "SHELLED"},
            {AFF_IMMUNITY,       "IMMUNITY"},
            {AFF_SPIRITCONTROL,  "SPIRITCONTROL"}
    };

}