//
// Created by volund on 6/20/22.
//

#ifndef RINGMUD_INCLUDE_RINGMUD_LEGACY_SONGS
#define RINGMUD_INCLUDE_RINGMUD_LEGACY_SONGS

/* Ocarina Songs */
#define SONG_SAFETY             1
#define SONG_SHIELDING          2
#define SONG_SHADOW_STITCH      3
#define SONG_TELEPORT_EARTH     4
#define SONG_TELEPORT_KONACK    5
#define SONG_TELEPORT_ARLIA     6
#define SONG_TELEPORT_NAMEK     7
#define SONG_TELEPORT_VEGETA    8
#define SONG_TELEPORT_FRIGID    9
#define SONG_TELEPORT_AETHER   10
#define SONG_TELEPORT_KANASSA  11

#endif //RINGMUD_INCLUDE_RINGMUD_LEGACY_SONGS
